### ISSUE TITLE
Endpoint get all Activities: Falta implementación correcta en la api

### ISSUE THREAD

**Issue by NikoleSpace** [Travel-Better-Company/safetrip-backend#10]
![error 6](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/bd01e089-bc6e-4b8b-82f1-44a3fee27de2)

**Comment by EstebanCabreraArbizu** [comment]
Eso no está implementado dentro del service ni tampoco se hace mención dentro del controller. Lo más similar a este es el de getAllActivitiesByItineraryId
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/11c7e66a-aab2-4d83-b248-b241a22d9daa)
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/963ad861-ab83-4356-81af-c81712450516)

**Comment by NikoleSpace** [comment]
Ya se implementó
![funcion get all activities Controller](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/2a0a2d08-e856-4232-9278-a3d2d77d9454)
![get activities postman](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/a7281b14-b359-434e-a2d6-74beb8ac857d)
