### ISSUE TITLE
Endpoint create Suscription: error al crear la subscripción

### ISSUE THREAD

**Issue by EstebanCabreraArbizu** [Travel-Better-Company/safetrip-backend#12]
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/2e07887e-12ce-4d41-a42e-45c16f1b7519)

Puede que sea al momento de crear la suscripción. Los errores se originan al hacer el guardado de la suscripción en el repositorio. Puede que ocurra al no tener validaciones dentro de la función:
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/8ffe96f8-4523-4034-8a93-2797e2850c56)

**Comment by EstebanCabreraArbizu** [comment]
Al parecer el error proviene al no tener una validación que compruebe si el userID ingresado ya está en otra suscripción dentro de la base de datos.
Es más dentro de la función createSubscription no se tiene validaciones o excepciones al ingresar el Id del usuario y guardarlo en la entidad. Solo retornan un valor nulo y no un mensaje de los exceptions.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/f3b1f642-5f06-427c-ade6-c528783a90de)

Otro caso es en su función de obtener las suscripción por ID, ya que no retorna ningún mensaje y solo manda null.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/74bfe68c-7b0d-4cdb-984f-f0298bebb847)

Por último, en el test de esa clase Service, en la función de crear una suscripción no se busca el usuario por el id ingresado, solo se crea un nuevo user y ya.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/0f05a213-6ca4-480e-861e-abe4aa0cf96b)

**Comment by EstebanCabreraArbizu** [comment]
Recomendaría también que en el response de la suscripción se retorne el response del user en lugar de solo su ID. De esta forma se comprueba de que se ha ingresado con éxito los datos y se haya interrelacionado las tablas del users y Subscription de forma correcta.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/09c0449e-ffc0-4623-9511-588bda065b2a)

**Comment by EstebanCabreraArbizu** [comment]
Otra recomendación a dar es que se use las etiquetas Data en lugar del Getter.
Esto para mantener un estándar de configuración en las clases y así ahorrar en codificar.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/4234f142-249d-47a0-aebb-42c2dae10728)
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/9b1dfaf1-8f12-4aee-b83d-2dd75987aca8)
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/600e3515-df32-4143-90cc-bd0aeba2c96e)

**Comment by FrancoSimonini** [comment]
Listo, los problemas ya fueron corregidos.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/81375893/baf4f9ac-d036-4543-a1c8-ad62674b8250)
Parece que los users no se asignaban apropiadamente

Este es el nuevo create subscription
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/81375893/035893de-7c6b-484c-a36f-db6545a9ed47)

Probando el el postman, se comprobó que el usuario retorna satisfactoriamente, al momento de crear suscripción
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/81375893/c4ea28f8-123b-4a8f-9b33-c6ea468913b1)
