### ISSUE TITLE
Endpoint Share itinerary: Falta probarlo

### ISSUE THREAD

**Issue by EstebanCabreraArbizu** [Travel-Better-Company/safetrip-backend#13]
Apenas solo se creo la tarea.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/b695bd49-00e3-4305-a453-ec3f0b6439cf)

**Comment by NikoleSpace** [comment]
Ya lo probé. La lógica funciona bien, copia el itinerario del usuario y lo pega creando uno nuevo con el nombre del user_target. Solo hay un pequeño problema de consistencia en la estructura de datos entre la solicitud y la respuesta. Debe ser porque no se mapearon bien los nombres entre Response y Request. 
![problema de consistencia en la estructura de datos](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/a3a6c6d6-eecf-4209-85f5-25147420fdf0)

**Comment by NikoleSpace** [comment]
Salía 0 porque se creaba un ResponseDTo vacío, Ya lo solucioné.
![basicanebte crea un SharingResponseDTO vacío entonces muestra 0 en los campos](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/dd7d8a4b-3af4-4ace-88be-5c8065366f32)
Luego de cambiarla ya se muestra correctamente
![ya se muestra correctamente share itinerary response](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/47bce5ca-fcab-4610-b529-10837e5d9e45)
