### ISSUE TITLE
FlighsRequestDTO: Faltan validaciones en el Request y  Service

### ISSUE THREAD

**Issue by EstebanCabreraArbizu** [Travel-Better-Company/safetrip-backend#14]
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/a5d67e8c-d272-4cfc-afb6-512d8f4cb01f)

**Comment by NikoleSpace** [comment]
Creo que lo de Flights hay que dejarlo como está porque de todos modos esa US esta pensada para utilizarla con una api externa y se supone que al usar la api externa obtendremos la información en tiempo real de la API externa cuando los usuarios realicen búsquedas. Y no deberíamos avanzar más en esa US porque también hay que comprender como funciona la api externa, y como ni la tenemos mejor ahi no más.

**Comment by EstebanCabreraArbizu** [comment]
Me parece bien, si mal no recuerdo la API que se elegio es la de LATAM. Solo faltaría buscar su API que se usa para registrar los vuelos y alojamientos
