### ISSUE TITLE
Endpoint create activity: no se puede crear mas de 1 actividad

### ISSUE THREAD

**Issue by NikoleSpace** [Travel-Better-Company/safetrip-backend#16]
por mas que cree diferentes actividades en el get all activities solo se ve 1, y en dbeaver también solo aparece registrado la ultima actividad registrada.

**Comment by EstebanCabreraArbizu** [comment]
Se corrigió este error al tener que hacer correctamente la convergencia entre el Activity y ActivityResponseDTO. Ya que faltaba colocar bien el nombre en ambas clases para que funcione bien el mapper.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/07e5de5c-866f-4227-89ab-4854af4bc5b8)
 Aparte, se colocó de forma explicita la conversión del activityRequestDTO a activity. Esto para ingresar de forma correcta el itinerario en el cuál está relacionado y se muestre en el postman.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/038c343b-6384-4353-87e4-52d101621b10)
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/00ecae33-7fa4-4dd1-a909-f0c6ccbdf670)
