### ISSUE TITLE
SubscriptionRequestDto le faltan validaciones

### ISSUE THREAD

**Issue by EstebanCabreraArbizu** [Travel-Better-Company/safetrip-backend#17]
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/7e99c381-d43b-4dac-9755-f47f498831d3)

**Comment by NikoleSpace** [comment]
@FrancoSimonini  ya lo agregó.
![validaciones suscription](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/da284a38-1b88-4c81-813a-6e127c85375c)
