### ISSUE TITLE
Activity Service: Falta colocar una validación acerca de las horas ingresadas

### ISSUE THREAD

**Issue by EstebanCabreraArbizu** [Travel-Better-Company/safetrip-backend#22]
Al momento de ejecutar el postman, se me permite ingresar en startime una hora mayor a la de endtime. Cosa que no tiene sentido
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/a0c8590b-ed1e-49de-b772-72145edc4de6)

**Comment by NikoleSpace** [comment]
Se cambió el operador lógico, ahora si valida bien. 
![operador logico](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/f95df919-7715-488b-a1bc-48b48d45b58a)
en el postman
![postman cerate activity](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/1dd3b7e5-db72-486c-bab9-9360c2f27b10)
