### ISSUE TITLE
Endpoint createCustomer: No sale El mensaje de ResourceAlreadyExistsException

### ISSUE THREAD

**Issue by NikoleSpace** [Travel-Better-Company/safetrip-backend#4]

**Comment by EstebanCabreraArbizu** [comment]
Al parecer es por un error de no colocar una clase dentro de los exceptions. Aquí dejo el link donde hablo un poco más de ello:
https://github.com/Travel-Better-Company/safetrip-backend/issues/6#issuecomment-1793110204

**Comment by NikoleSpace** [comment]
el mensaje ya aparece. Solucionado y comprobado.
![comprobacion mensaje create user](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/45552428-ebb3-4057-acb1-84516a638bc3)
