### ISSUE TITLE
Endpoint followUser: Error al probarlo

### ISSUE THREAD

**Issue by NikoleSpace** [Travel-Better-Company/safetrip-backend#5]
![error 1](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/887026dc-01cd-42ab-ac67-f127b049a9bd)

**Comment by EstebanCabreraArbizu** [comment]
Me aparece dentro del postman.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/503389a8-3199-46f1-82e1-7628bfcfa69c)

**Comment by NikoleSpace** [comment]
Si funciona.
