### ISSUE TITLE
Endpoint createItinerary : No sale Mensaje de ResourceNotFoundException

### ISSUE THREAD

**Issue by NikoleSpace** [Travel-Better-Company/safetrip-backend#6]
![error 2](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/d289d085-a605-4402-84e8-a7cc5db0ef84)

**Comment by EstebanCabreraArbizu** [comment]
Eso si es raro, en sí si salen los errores de validación. Sin embargo, no salen los mensajes de error que se han colocado dentro del service.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/aa2c4043-5cf9-4e0c-8050-d88355ceda84)

**Comment by EstebanCabreraArbizu** [comment]
Eh visto y lo que sucede es que no hay una clase que maneja los mensajes de errores personalizados dentro de nuestro proyecto. 
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/65bfca51-72f7-427c-9416-7a275468c3fa)
Así que lo eh creado en base al ejemplo de bookings del profesor.
Este es el resultado:
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/3487fb4a-d8c8-4bc6-91fa-ba2f00d62ab1)

Lo logré hacer colocando la clase Handler junto a una modificación del clase ErrorDTO:
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/547ab5f3-6264-4e12-bfcf-631bd0f61e1e)

![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/f2251e7f-e896-49b0-b6bd-54f346a5a423)
Aprovechando también mejore un poco la clase service de itinerario al ya validar las clase request y no la entity, para así obtener un mejor filtrado.

![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/a6a0a04e-5d95-4929-8823-1d2079d4a4e8)

**Comment by NikoleSpace** [comment]
solucionado y comprobado
![solucion crear itinerario con el mismo nombre](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/41ee700e-ed8e-48e2-a58a-8defec9c01cc)
