### ISSUE TITLE
Endpoint find itinerarie by location: Error al probar

### ISSUE THREAD

**Issue by NikoleSpace** [Travel-Better-Company/safetrip-backend#7]
![error 3](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/9fa47c5d-e794-46e1-b926-3c1d4d2f5519)

**Comment by EstebanCabreraArbizu** [comment]
Se tiene que primero crear un itinerario. Lo acabo de hacer y si aparece, también se debe colocar la ciudad dentro de la url en lugar de crear una key
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/a70679e6-2d8c-4dc1-b6cc-75e150504400)

**Comment by NikoleSpace** [comment]
Cuando se quiere crear un itinerario con un nombre que ya existe no quiere, aunque sea de un usuario diferente. Y en "user" siempre sale null

**Comment by NikoleSpace** [comment]
Para  "user" deje de mostrar solo null,  solo era cambiar el nombre en el ReponseDTO. Y para crear un itinerario con el mismo nombre pero diferente usuario se agregó un método en Repository y en el service.
![solucion find - user](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/c8f30ced-7112-4b21-8d7f-adee35b9114a)
![solucion crear itinerario con el mismo nombre](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/01f14987-176e-417a-80a0-9fd5fad50304)
