### ISSUE TITLE
Endpoint get Activities by ID Itinerary: Falta implementar correctamente en la api

### ISSUE THREAD

**Issue by NikoleSpace** [Travel-Better-Company/safetrip-backend#8]
![error 4](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/759be7f4-eddf-488c-8f4b-7d126d5c6c8d)

**Comment by EstebanCabreraArbizu** [comment]
Esto se debe a que no se han ingresado algún itinerario. Además su path mostrado en la captura está mal implementado:
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/ac73d9c4-c191-43da-8bf5-556135ea82cc)

Sería mejor probarlo con un itinerario existente para ver si no sale un error en el servidor

**Comment by EstebanCabreraArbizu** [comment]
Se soluciono este al corregir primero el crear una actividad dentro de ActivityService.
Al parecer no ingresaba el itinerario al no poder hacer una convergencia correcta. Se corrigió al cambiar el nombre y cambiar su tipo a uno response.
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/1faf2fa7-0f9c-4284-99a1-28ddc41f115b)
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/8d601f08-639c-4324-8d33-488cf6ed1b35)
