### ISSUE TITLE
Endpoint get all subscriptions: error

### ISSUE THREAD

**Issue by NikoleSpace** [Travel-Better-Company/safetrip-backend#9]
![error 5](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/143635da-214c-45c3-95a1-b7c6cd8b0c28)

**Comment by EstebanCabreraArbizu** [comment]
Al usar la base de datos dentro de AWS si sale las subscripciones:
![image](https://github.com/Travel-Better-Company/safetrip-backend/assets/86165162/0ff36c98-a007-46f0-9b83-ab4d8c4b5247)

**Comment by NikoleSpace** [comment]
Despues de probar varias veces en postman, accediendo de la base de datos en la nube, me di cuenta que por ratos no se puede acceder pero si espero un momento ya se reestablece la conexión.

![pruebas nube](https://github.com/Travel-Better-Company/safetrip-backend/assets/129306932/bcf68c5a-f020-4b89-b41c-5e8177f1271d)
